SELECT
	TRACT10,
	SUM(POP_TOT) AS POP_SUM,
	SUM(CASE WHEN DIST_BUS < 999
		THEN POP_TOT 
		ELSE NULL END) AS POP_BUS_TOT,
	SUM(CASE WHEN DIST_LRT < 999
		THEN POP_TOT 
		ELSE NULL END) AS POP_TRN_TOT,
	SUM(CASE WHEN DIST_MIN < 999
		THEN POP_TOT 
		ELSE NULL END) AS POP_MIN_TOT,
	CASE
		WHEN SUM(POP_TOT) = 0 THEN 0
		ELSE SUM(POP_TOT*NODES1H)/SUM(POP_TOT) 
		END AS NODES1H,
	CASE WHEN SUM(CASE WHEN DIST_BUS < 999 THEN POP_TOT ELSE NULL END) = 0 THEN 0 
		ELSE SUM(CASE WHEN DIST_BUS < 999
			THEN POP_TOT * DIST_BUS
			ELSE NULL END) / 
			SUM(CASE WHEN DIST_BUS < 999
			THEN POP_TOT 
			ELSE NULL END)
		END AS DIST_BUS
FROM ilut_combined2016_2
GROUP BY TRACT10
ORDER BY SUM(POP_TOT)