
CREATE TABLE {} ( --table name
	[id] [int] NULL,
	[tour_id] [int] NULL,
	[hhno] [int] NULL,
	[pno] [smallint] NULL,
	[day] [smallint] NULL,
	[tour] [smallint] NULL,
	[half] [smallint] NULL,
	[tseg] [smallint] NULL,
	[tsvid] [smallint] NULL,
	[opurp] [smallint] NULL,
	[dpurp] [smallint] NULL,
	[oadtyp] [smallint] NULL,
	[dadtyp] [smallint] NULL,
	[opcl] [int] NULL,
	[otaz] [smallint] NULL,
	[dpcl] [int] NULL,
	[dtaz] [smallint] NULL,
	[mode] [smallint] NULL,
	[pathtype] [smallint] NULL,
	[dorp] [smallint] NULL,
	[deptm] [smallint] NULL,
	[arrtm] [smallint] NULL,
	[endacttm] [smallint] NULL,
	[travtime] [real] NULL,
	[travcost] [real] NULL,
	[travdist] [real] NULL,
	[vot] [real] NULL,
	[trexpfac] [smallint] NULL,
	timeau	[real],
	distau	[real],
	distcong	[real]
) 

